TeamDjango/TeamDjango/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url, include

urlpatterns = [
    #path('multidestination/', include('multidestination.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('multidestination.urls')),
]

TeamDjango/multidestination/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('search/<str:dest>/', views.results, name='results'),
    url(r'^home/$', views.home, name='home'),
    url(r'^tripRoad/$', views.trip, name='road'),

 ]

TeamDjango/multidestination/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class TripHotelSearch(models.Model):
    trip = models.AutoField(primary_key=True)
    city_1 = models.CharField(max_length = 100, blank=True)
    checkin_1 = models.DateField()
    checkout_1 = models.DateField()
    numberOfPersons_1 = models.CharField(max_length = 140)
    city_2 = models.CharField(max_length = 100, blank=True)
    checkin_2 = models.DateField()
    checkout_2 = models.DateField()
    numberOfPersons_2 = models.CharField(max_length = 140)
    city_3 = models.CharField(max_length = 100, blank=True)
    checkin_3 = models.DateField()
    checkout_3 = models.DateField()
    numberOfPersons_3 = models.CharField(max_length = 140)

    budget = models.IntegerField()

    def __str__(self):
        return str(self.city)

TeamDjango/multidestination/forms.py
from django import forms
from multidestination.models import TripHotelSearch

class TripHotelSearchForm(forms.ModelForm):
    class Meta:
        model = TripHotelSearch
        fields = ('city_1', 'checkin_1','checkout_1','numberOfPersons_1','city_2', 'checkin_2','checkout_2','numberOfPersons_2',
        'city_3', 'checkin_3','checkout_3','numberOfPersons_3','budget')  
    
    def clean_cityName(self): 
        return self.cleaned_data['city']
        
    def __init__(self, *args, **kwargs):
        super(TripHotelSearchForm, self).__init__(*args, **kwargs)
        self.fields[ 'checkin_1' ].input_formats = [ '%Y-%m-%d' ]
        self.fields[ 'checkout_1' ].input_formats = [ '%Y-%m-%d' ]
        self.fields[ 'checkin_2' ].input_formats = [ '%Y-%m-%d' ]
        self.fields[ 'checkout_2' ].input_formats = [ '%Y-%m-%d' ]
        self.fields[ 'checkin_3' ].input_formats = [ '%Y-%m-%d' ]
        self.fields[ 'checkout_3' ].input_formats = [ '%Y-%m-%d' ]

TeamDjango/multidestination/views.py
from django.shortcuts import render, redirect
import requests
from django.http import HttpResponse
from django.shortcuts import render
from multidestination.forms import TripHotelSearchForm
from django.http import JsonResponse
url = "https://distribution-xml.booking.com/2.0/json/countries"

headers = {
    'Authorization': "Basic d29tZW5pbnRlY2gyMDE4OjJEY2RDWm5UZmo=",
    'cache-control': "no-cache",
    'Postman-Token': "8239643c-8d84-4d54-b34f-c5ff77d37750"
}


def index(request):
    return render(request, 'home.html')


def home(request):
    print("here")
    print(request.method)
    if (request.method == 'POST'):
        form = TripHotelSearchForm(request.POST)
        # response = requests.request("GET", url, headers=headers)
        print(form.errors)
        if (form.is_valid()):
            hotelform = form.save(commit=False)
            hotelform.save()
            # print (request.POST)

            city1 = request.POST['city_1']
            checkin_date1 = request.POST['checkin_1']
            checout_date1 = request.POST['checkout_1']
            print(checout_date1)
            nub_pers1 = request.POST['numberOfPersons_1']

            city2 = request.POST['city_2']
            checkin_date2 = request.POST['checkin_2']
            checout_date2 = request.POST['checkout_2']
            nub_pers2 = request.POST['numberOfPersons_2']

            city3 = request.POST['city_3']
            checkin_date3 = request.POST['checkin_3']
            checout_date3 = request.POST['checkout_3']
            nub_pers3 = request.POST['numberOfPersons_3']

            #getcity details
            cityId1 = getCityID(city1)
            hoteldetails1 = getHotelAvailability(cityId1,checkin_date1,checout_date1)

            cityId2 = getCityID(city2)
            hoteldetails2 = getHotelAvailability(cityId2, checkin_date2, checout_date2)

            cityId3 = getCityID(city3)
            print(cityId3)
            hoteldetails3 = getHotelAvailability(cityId3, checkin_date3, checout_date3)

            budget = request.POST['budget']
            print(city1, city2, city3)
            #return JsonResponse(hoteldetails3)
            args = {'c1':city1,'c2':city2,'c3':city3,
                'checkin_date1': checkin_date1,'checkin_date2': checkin_date2,'checkin_date3': checkin_date3,
                'checout_date1': checout_date1, 'checout_date2': checout_date2, 'checout_date3': checout_date3, 
             'h1': hoteldetails1.json(),'h2': HttpResponse(hoteldetails2),'h3': HttpResponse(hoteldetails3) }
            #{'tripId' :tripId}
            return render(request,'tripRoad.html', args)
            #return HttpResponse(hoteldetails3)
            #return render(request, 'tripRoad.html')
    else:
        form = TripHotelSearchForm()

    args = {'form': form}
    return render(request, 'home.html', args)


def trip(request):
    return render(request, 'tripRoad.html')


def getCityID(dest):
    api = findBookingAPI("searchCity")
    res = results(api,dest)
    for item in res:
        if item['type'] == 'city':
            return item[id]
    return res[-1]['city_ufi']

    return results(api,dest)


def getHotelAvailability(cityid, checkin, checkout):
    api = findBookingAPI("HotelAvailability")
    qryParams = {"checkin":checkin,"checkout":checkout, "city_ids":cityid, "room1":'A,A', "extras":""}
    headers = {
        'authorization': "Basic d29tZW5pbnRlY2gyMDE4OjJEY2RDWm5UZmo=",
        'cache-control': "no-cache",
        'postman-token': "25ba4d68-b138-6a20-605d-c44b22c976a5"
    }
    response = requests.request("GET", api, headers=headers, params=qryParams)
    return response


def results(api,dest):
    #api = findBookingAPI(request.path.split('/')[2])
    qryParams = {"language":"en_US","text":"\"+dest+\""}


    headers = {
        'authorization': "Basic d29tZW5pbnRlY2gyMDE4OjJEY2RDWm5UZmo=",
        'cache-control': "no-cache",
        'postman-token': "25ba4d68-b138-6a20-605d-c44b22c976a5"
    }

    response = requests.request("GET", api, headers=headers, params=qryParams)

    #return HttpResponse(response)
    return response.json()["result"]
def findBookingAPI(path):
    APIDict = {
        'searchCity':"https://distribution-xml.booking.com/2.2/json/autocomplete",
        'HotelAvailability':"https://distribution-xml.booking.com/2.2/json/hotelAvailability"
    }
    return APIDict[path]

def getResponse(url):
    response = requests.get(url)
    return response

TeamDjango/multidestination/templates/header.html
<style>
  header {
    background-color: #003580;
    color: white;
    height: 50px;
    padding: 12px 80px;
  }
  #logo {
    height: 25px;
    background-size: contain;
    margin-top: 14px;
  }
</style>

{% load static %}

<header>
  <img id="logo" src="{% static "bookinglogo.png" %}">
</header>

TeamDjango/multidestination/templates/home.html
{% include "header.html" %}
{% include "searchForm.html" %}

TeamDjango/multidestination/templates/searchForm.html
<style>
  #sitePrint {
    background-size: contain;
    max-width: 100%;
    max-height: 100%;
  }
  #searchForm {
    background-color: #F7F7F7;
    padding: 1px 80px 25px 80px;
    font-family: BlinkMacSystemFont,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  }
  #mainTitle {
    color: #383838;
    font-weight: bold;
    font-size: 24px;
  }
  #secondaryTitle {
    color: #383838;
    font-size: 14px;
  }
  #inputContainer {
    padding: 24px 0;
    display: flex;
    justify-content: center;
    flex-direction: column;
  }
  .customInput {
    border: none;
    outline: 3px solid #febb02;
    height: 52px;
    padding: 3px;
    flex-grow: 1;
    box-sizing: content-box;
    outline-offset: 0;
  }
  #buttonsContainer {
    display: flex;
    align-items: flex-end;
  }
  #searchBtn {
    height: 45px;
    width: 144.52px;
    border-radius: 3px;
    background-color: #0077CC;
    border: none;
    color: white;
    font-size: 20px;
    font-weight: 500;
    letter-spacing: -0.37px;
    line-height: 26px;
    cursor: pointer;
  }
  #add {
    height: 45px;
    width: 278px;
    border-radius: 3px;
    background-color: #067812;
    border: none;
    color: white;
    font-size: 20px;
    font-weight: 500;
    letter-spacing: -0.37px;
    line-height: 26px;
    cursor: pointer;
  }
  #id_budget {
    border: 1px solid #DBDBDB;
    border-radius: 3px;
    height: 46px;	width: 182px;
  }
  #budgetHint {
    font-size: 15px;
    letter-spacing: -0.28px;
    line-height: 20px;
  }
  #budgetContainer {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    margin-left: 13px;
  }
  .searchItem {
    display: flex;
    justify-content: center;
  }
  .removeBtn {
    font-size: 14px;
    display: inline-block;
    width: 52px;
    text-align: right;
    line-height: 52px;
    font-weight: bold;
    color: #0077CC;
    cursor: pointer;
  }
</style>
<script>

window.onload = function() {
  const container = document.querySelector('#inputContainer');
  const add = document.querySelector('#add');
  let totalSearches = 1;
  const maxSearches = 3;
  function getRemoveBtn(id) {
    const removeBtn = document.createElement('span');
    removeBtn.id = id;
    removeBtn.classList.add('removeBtn');
    removeBtn.innerHTML = 'X';
    removeBtn.addEventListener('click', (event) => {
      event.preventDefault();
      if (totalSearches === 1) {
        return;
      }
      const searchItemIdToRemove = event.target.id.split('_remove')[0];
      console.log('event target:', searchItemIdToRemove);
      const el = document.querySelector('#' + searchItemIdToRemove);
      el.parentNode.removeChild(el);
      totalSearches -= 1;
      if (totalSearches === 1) {
        const remEl = document.querySelector('#' + 'search_' + totalSearches + '_remove');
        remEl.parentNode.removeChild(remEl);
      }
    }, false);
    return removeBtn;
  }
  add.addEventListener('click', (event) => {
    event.preventDefault();
    var fragment = document.createDocumentFragment();
    var previousSearchItem = document.querySelector('#search_' + totalSearches);
    var prevVal = previousSearchItem.children[2].value;
    if (totalSearches === maxSearches) {
      return;
    }
    if (!prevVal) {
      return;
    }

    if (totalSearches === 1) {
      previousSearchItem.appendChild(getRemoveBtn('search_' + totalSearches + '_remove'));
    }

    var previousDate = new Date(prevVal);
    previousDate.setDate(previousDate.getDate() + 1);
    totalSearches += 1;
    var searchContainers = document.createElement('div');
    searchContainers.id = 'search_' + totalSearches;
    searchContainers.classList.add('searchItem');

    var city = document.createElement('input');
    city.type = 'text';
    city.name = 'city_' + totalSearches;
    city.placeholder = 'Select a location';
    city.classList.add('customInput');
    fragment.appendChild(city);

    var checkin = document.createElement('input');
    checkin.type = 'date';
    checkin.name = 'checkin_' + totalSearches;
    checkin.value = previousDate.toISOString().substring(0, 10);
    checkin.classList.add('customInput');
    fragment.appendChild(checkin);

    var checkout = document.createElement('input');
    checkout.type = 'date';
    checkout.name = 'checkout_' + totalSearches;
    checkout.classList.add('customInput');
    previousDate.setDate(previousDate.getDate() + 1);
    checkout.value = previousDate.toISOString().substring(0, 10);
    fragment.appendChild(checkout);

    var type = document.createElement('input');
    type.type = 'text';
    type.name = 'numberOfPersons_' + totalSearches;
    type.classList.add('customInput');
    fragment.appendChild(type);

    fragment.appendChild(getRemoveBtn('search_' + totalSearches + '_remove'));

    searchContainers.appendChild(fragment);
    container.appendChild(searchContainers);
  }, false);
};
</script>

<form id="searchForm" method="post">
  {% csrf_token %}
   <p id="mainTitle">Find Deals for Any Season</p>
   <p id="secondaryTitle" >From cozy country homes to funky apartments</p>
   <div id="inputContainer">
      <div id="search_1" class="searchItem">
        <input type="text" class="customInput"  name="city_1" maxlength="100"  placeholder="Select a location" />
        <input type="date" class="customInput" name="checkin_1" value="2018-10-09" required  placeholder="Select a start date" />
        <input type="date" class="customInput"  name="checkout_1" value="2018-10-09" required  placeholder="Select a end date" />
        <input type="text" name="numberOfPersons_1" maxlength="140" required id="id_numberOfPersons" class="customInput" />
      </div>

   </div>
   <div id="buttonsContainer">
     <button id="add">+ Add another destination</button>
     <div id="budgetContainer">
       <span id="budgetHint">Budget for entire trip</span>
       <input type="number" name="budget" required id="id_budget"/>
     </div>
     <input id="searchBtn" type="submit" value="Search">
   </div>
</form>

{% load static %}
<img id="sitePrint" src="{% static "sitePrint.png" %}">

TeamDjango/multidestination/templates/searchHotel.html
<!DOCTYPE html>

{% include "header.html" %}
{% include "searchForm.html" %}
<html>
<body>

<form action="/multidestination/home/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

TeamDjango/multidestination/templates/tripRoad.html
{% include "header.html" %}
<style>
  #tripPlanContainer {
    min-height: 100px;
    background-color: #E9F0FA;
    padding: 20px 80px;
    font-family: BlinkMacSystemFont,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  }
  .mainTitle {
    color: #383838;
    font-weight: bold;
    font-size: 16px;
  }
  .secondaryTitle {
    color: #383838;
    font-size: 14px;
  }
  .destinationContainer {
    width: 210px;
    background-color: #FFFFFF;
    border-radius: 2px;
    text-align: center;
    padding-top: 2px;
  }
  .selected {
    border-bottom: 5px solid #0077CC;
  }

  #destinations {
    display: flex;
    justify-content: space-between;
  }

</style>
<script type="text/javascript"> 
  window.onload = function() {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    function formatDate(dateString1, dateString2) {
      var d1 = new Date(dateString1);
      var d2 = new Date(dateString2);
      return months[d1.getMonth()] + ' ' + d1.getDate()  + ' - ' +   months[d2.getMonth()] + ' ' + d2.getDate();
    }
    const firstDest = document.querySelector('#c1');
    firstDest.innerHTML = formatDate("{{checkin_date1}}", "{{checout_date1}}");
    const secondDest = document.querySelector('#c2');
    secondDest.innerHTML = formatDate("{{checkin_date2}}", "{{checout_date2}}");
    const thirdDest = document.querySelector('#c3');
    thirdDest.innerHTML = formatDate("{{checkin_date3}}", "{{checout_date3}}");
  }
</script>
<div id="tripPlanContainer">
  <p class="mainTitle">Your Trip Planner</p>
  <div id="destinations">
      <div id="destination_1" class="destinationContainer selected">
          <p class="mainTitle" >{{c1}}</p>
          <p class="secondaryTitle" id="c1"> {{checkin_date1}} | {{checout_date1}} </p>
      </div> 
      <div id="destination_2" class="destinationContainer">
          <p class="mainTitle">{{c2}}</p>
          <p class="secondaryTitle"  id="c2">{{checkin_date2}} | {{checout_date2}} </p>
      </div> 
      <div id="destination_3" class="destinationContainer">
          <p class="mainTitle">{{c3}}</p>
          <p class="secondaryTitle"  id="c3">{{checkin_date3}} | {{checout_date3}} </p>
      </div> 
  </div>
</div>

<div>
    {{ h1 }}
</div>